language: ruby
cache:
  bundler: true
  apt: true

sudo: required
dist: trusty

rvm:
  - 2.4.2

env:
  global:
    - RACK_ENV=test

before_install:
  - cp config/database.yml.example config/database.yml
  - cp config/credentials.yml.example config/credentials.yml
  - mkdir -p ./tmp/cache

bundler_args: --without metrics --deployment

before_script:
  - bundle exec rake db:create db:migrate

script:
  - bundle exec rspec spec
