* Testing
** Unit tests and cucumber tests

* Bugs
** Error message if you go to credence page when not logged in
*** Should you be able to play when not logged in?
**** If so, should it keep your progress if you then create an account, or log in having not played the game while logged in?
***** (That's definitely not MVP worthy.)
**** Probably don't bother for first iteration.
** Some answers have the same value. They shouldn't both be selected.
*** If we do this by rejecting the second answer in pick_random, then we need to swap answer0 and answer1 half the time. Otherwise the distribution isn't uniform: answer0 is more likely to be one with multiple equal-valued answers.
*** Work out how to test for this before fixing it.
** CredenceQuestion.pick_random doesn't consider CredenceQuestionGenerator.weight
*** How does the original game do it?
** If you click an answer twice (or two different answers quickly), both count - the first answers the question you were given, and the second answers the next question, that you didn't see yet.
*** Probably the way to solve this, is to have a hidden 'question id' field. If the submitted id isn't the same as the current question id, ignore the submission.
**** Do we need to worry about persisting the flash?

* Graphs
** Probably make the user take explicit action to view them.
** Unless/until there's a reason to deviate, they should probably look the same as the existing ones.
*** Rendered with google chart API, see app/models/statistics.rb

* How do you create db indexes in rails?
** N.B. An index on (A, B) can be used to search for A or A,B, but not B. So credence_questions should probably have an index on (credence_game_id, asked_at).
** http://stackoverflow.com/questions/6242304/best-way-to-add-index-to-database
*** Multi-column indexes: replace `:col` with `[:col1, :col2]`.

* This question:

	Which US state had a higher percentage of adults commuting to work by public transportation in 2010?

is ambiguous. I think it's asking: of people commuting to work, how many do it by public transportation? The answer is given in "% of commuting workers", which fits. But the reference class isn't obvious from the question, and sounds like it should just be "adults".

* Scores should be in a DL, not a TABLE, if I can style it properly.

* Add debug flag to CredenceGame - if not enabled, make 'delete progress' harder to find, and don't show answers with a question.

* Put a link on the main page.
