* Testing
** Unit tests
*** How do I test the controller?
** Cucumber tests
*** How do I create these?

* Bugs
** CredenceQuestion.pick_random doesn't consider CredenceQuestionGenerator.weight
*** How does the original game do it?
** It's possible for a user to get asked the same question twice.
*** There are enough questions that this isn't a big deal.

* This question:

	Which US state had a higher percentage of adults commuting to work by public transportation in 2010?

is ambiguous. I think it's asking: of people commuting to work, how many do it by public transportation? The answer is given in "% of commuting workers", which fits. But the reference class isn't obvious from the question, and sounds like it should just be "adults".

* Typo:

      Each of the following European rivers is among the 175 longest in the
        world. Which one s [sic] longer?

* Does the charset in the .xml files (which is currently not utf-8) affect the encoding in the db (which I don't know what it is)?

* Merge master into credence game.

* Add way to delete credence game data, possibly from settings page.
