* Testing
** Unit tests and cucumber tests

* Bugs
** Error message if you go to credence page when not logged in
*** Should you be able to play when not logged in?
**** If so, should it keep your progress if you then create an account, or log in having not played the game while logged in?
***** (That's definitely not MVP worthy.)
**** Probably don't bother for first iteration.
** CredenceQuestion.pick_random doesn't consider CredenceQuestionGenerator.weight
*** How does the original game do it?
** It's possible for a user to get asked the same question twice.
*** There are enough questions that this isn't a big deal.

* Graphs
** Probably make the user take explicit action to view them.
** Unless/until there's a reason to deviate, they should probably look the same as the existing ones.
*** Rendered with google chart API, see app/models/statistics.rb

* How do you create db indexes in rails?
** N.B. An index on (A, B) can be used to search for A or A,B, but not B. So credence_questions should probably have an index on (credence_game_id, asked_at).
** http://stackoverflow.com/questions/6242304/best-way-to-add-index-to-database
*** Multi-column indexes: replace `:col` with `[:col1, :col2]`.

* This question:

	Which US state had a higher percentage of adults commuting to work by public transportation in 2010?

is ambiguous. I think it's asking: of people commuting to work, how many do it by public transportation? The answer is given in "% of commuting workers", which fits. But the reference class isn't obvious from the question, and sounds like it should just be "adults".

* Scores should be in a DL, not a TABLE, if I can style it properly.

* Add debug flag to CredenceGame - if not enabled, make 'delete progress' harder to find, and don't show answers with a question.

* Put a link on the main page.
