* Testing
** Unit tests and cucumber tests

* Bugs
** Error message if you go to credence page when not logged in
*** Should you be able to play when not logged in?
**** If so, should it keep your progress if you then create an account, or log in having not played the game while logged in?
***** (That's definitely not MVP worthy.)
**** Probably don't bother for first iteration.
** CredenceQuestion.pick_random doesn't consider CredenceQuestionGenerator.weight
*** How does the original game do it?
** It's possible for a user to get asked the same question twice.
*** There are enough questions that this isn't a big deal.

* This question:

	Which US state had a higher percentage of adults commuting to work by public transportation in 2010?

is ambiguous. I think it's asking: of people commuting to work, how many do it by public transportation? The answer is given in "% of commuting workers", which fits. But the reference class isn't obvious from the question, and sounds like it should just be "adults".

* Scores should be in a DL, not a TABLE, if I can style it properly.

* Add way to delete credence game data, possibly from settings page.

* Put a link on the main page.
