# Use the README file as a reference to customize settings.

User:
  fields:
    default: login, name, email, updated_at, admin
    form: login, name, email, admin
  relationships: 
  application: Application

