pid: tmp/pids/thin.pid
wait: 30
timeout: 600
log: log/thin.log
max_conns: 1024
require: []
max_persistent_conns: 512
environment: production
daemonize: true

servers: 1
port: 9001

# Use this when using a sock file based load balancer like NGinx
#socket: /tmp/thin.sock
