name: RSpec Test Suite

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Linux dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y libpq-dev
    - name: Checkout branch
      uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.3
    - name: Install system packages
      run: (bundler -v | grep "2.0.2") || gem install bundler:2.0.2
    - name: Cache gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.OS }}-gem-cache-${{ hashFiles('Gemfile.lock') }}
        restore-keys: |
          ${{ runner.OS }}-gem-cache-
    - name: Install gems
      run: bundle install --jobs $(nproc) --retry 3 --without metrics --deployment
    - name: Set database settings
      run: cp config/database.yml.example config/database.yml
    - name: Set credentials
      run: cp config/credentials.yml.example config/credentials.yml
    - name: Create cache directory
      run: mkdir -p ./tmp/cache
    - name: Set up database
      run: RAILS_ENV=test bundle exec rake db:create db:migrate
    - name: Run RSpec test suite
      run: bundle exec rspec spec
