name: RSpec Test Suite

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          # will assign a random free host port
          - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Install Linux dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y libpq-dev
    - name: Checkout branch
      uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.3
    - name: Install system packages
      run: (bundler -v | grep "2.0.2") || gem install bundler:2.0.2
    - name: Cache gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.OS }}-gem-cache-${{ hashFiles('Gemfile.lock') }}
        restore-keys: |
          ${{ runner.OS }}-gem-cache-
    - name: Install gems
      run: bundle install --jobs $(nproc) --retry 3 --without metrics --deployment
    - name: Set database settings
      run: cp config/database.yml.example config/database.yml
    - name: Set credentials
      run: cp config/credentials.yml.example config/credentials.yml
    - name: Create cache directory
      run: mkdir -p ./tmp/cache
    - name: Set up database
      run: bundle exec rake db:create db:migrate
    - name: Run RSpec test suite
      run: bundle exec rspec spec
    env:
      RAILS_ENV: test
      POSTGRES_HOST: localhost
      POSTGRES_PORT: ${{ build.services.postgres.ports[5432] }}
